### ISSUE TITLE
No output created when build

### ISSUE THREAD

**Issue by jojoblackFr** [AsherGlick/ResourceCalculator#101]
When I build with build.py no output is created
![image](https://github.com/AsherGlick/ResourceCalculator/assets/57195692/3fd5e743-07b3-443a-8148-a3c081d7b1d2)
![image](https://github.com/AsherGlick/ResourceCalculator/assets/57195692/a962b261-c352-4e51-b571-1ce62cb1c815)
(I'm working on a terratech tab)

**Comment by AsherGlick** [comment]
I would expect that you should receive a large amount of stdout text in addition to output files. Barring that I would expect to see an error print out on the console saying something went wrong. This makes me think that something is wrong with how python is setup on your computer. On windows I would try using the docker build system instead because that will rule out any dependency or install issues.
![Screenshot from 2023-07-02 11-38-02](https://github.com/AsherGlick/ResourceCalculator/assets/603989/86d545a7-bb35-4fbe-b082-14186b72f2bd)

Later in the build process other dependencies will be needed for png compression, typescript compiling, and gzipping, all of those will be automatically handled in the docker system but will need to be manually installed without it.

**Comment by jojoblackFr** [comment]
gonna try that and reach you after

**Comment by jojoblackFr** [comment]
docker doesn't work for some strange reason so i went to look in the build.py and found out that "core_resource_paths()" has never been called on my side
