### ISSUE TITLE
Minecraft 1.16 (Nether Update) items missing

### ISSUE THREAD

**Issue by mmodrow** [AsherGlick/ResourceCalculator#16]
I wanted to plan a Minecraft build with to this tool, but couldn't because of missing items.
I was explicitly missing blackstone and basalt, so I guess the Nether Update items are still missing here?

**Comment by mmodrow** [comment]
Just noticed, that the stone cutter is missing. For stone stairs it is more efficient (https://minecraft.fandom.com/wiki/Stonecutter#Cutting), this should be considered as well.

**Comment by TheBanditOfRed** [comment]
Hey im currently working on updating all the code to include all the blocks add up to 1.17 but currently I've had to put it on the back burner. I wouldnt expect it to be done any time soon so what i would suggest is to pick similar blocks to the ones you need and just remember to get the correct blocks (thats what i did until i got fed up and started updating the code).

**Comment by mmodrow** [comment]
That's what I did so far. Would you accept a PR, if I have the time?

**Comment by AsherGlick** [comment]
I probably would not be able to get around to reviewing it until the weekend after you submitted it but I will happily accept and release a PR to update any item list to make it more accurate or up to date.

**Comment by mmodrow** [comment]
As far as I could tell it would "only" be an update to the resource yaml file (and some image files), not the actual code, correct? I will see what I can do.

**Comment by AsherGlick** [comment]
If all you are doing is adding items and recipes, or changing recipes then yes that should be the only files you will need to change. Running `build.py` should take care of all of the logic for building the calculator page assuming the resource list file and the images are all present and correct, if something is wrong it should print out an error or warning to help debug what the issue is.
