### ISSUE TITLE
Minecraft: coal gives wrong amount of fuel

### ISSUE THREAD

**Issue by HVMarci** [AsherGlick/ResourceCalculator#17]
The Minecraft calculator says:
`Treat 8 coal as 1 (Stack) fuel`
Insead of:
`Treat 1 coal as 8 (Stack) fuel`

**Comment by AsherGlick** [comment]
The calculator is coded for the correct amount of fuel per coal. EG: https://resourcecalculator.com/minecraft/#steak=1

The issue is that "fuel" is an arbitrary concept and the calculator thinks you can have a stack of fuel (64 fuel) which is not a real thing. EG: https://resourcecalculator.com/minecraft/#steak=64 . This is confusing, and definitely a bug.

Stacking calculations need to be given a bit of attention so that items that cannot stack (swords, armor, fuel, etc) and things that have a unique stack size other then 64 (eggs, snowballs, etc) can be displayed properly in the output.

**Comment by AsherGlick** [comment]
New system makes this display clearer, it will always display the real count and a summary of stack sizes.
![Screenshot from 2021-04-16 23-25-53](https://user-images.githubusercontent.com/603989/115101613-4968e580-9f0b-11eb-9f44-44438a1af58d.png)

Should be live now but may still be cached to the old version in your browser. You can clear the cache manually or wait for it to expire to see it.
