### ISSUE TITLE
How do i use litematica plugin

### ISSUE THREAD

**Issue by xNorbig** [AsherGlick/ResourceCalculator#53]
I see that in repository there is option to import my litematice blocks list and it will do the job, but what is the link for it? i cannot find it

**Comment by AsherGlick** [comment]
https://resourcecalculator.com/minecraft/plugins/litematica/
The plugin was written by a contributor and is not directly linked from the site itself so that there is no expectation of maintenance in the event of a breaking change to the core site or to litematica. While still allowing it to be hosted for those who want to use it. See #42 for more info.
